version: "3.7"

services:

  etcd:
    image: "${CI_DOCKER_REGISTRY}/gms-common/etcd:${VERSION}"
    restart: on-failure
    networks:
      - kafka-net

  kafka:
    image: "${CI_DOCKER_REGISTRY}/confluentinc/cp-kafka:5.0.0"
    container_name: kafka
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:      
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "soh.station-soh:1:1,soh.capability-rollup:1:1,soh.ui-materialized-view:1:1,soh.ack-station-soh:1:1,soh.quieted-list:1:1,system.system-messages:1:1"
    depends_on:
      - zookeeper

  zookeeper:
    image: "${CI_DOCKER_REGISTRY}/confluentinc/cp-zookeeper:5.0.0"
    container_name: zookeeper
    networks:
      - kafka-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

networks:
  kafka-net:
    name: kafka-net
    attachable: true
