{{- $appName := "bastion" }}
{{- $appValues := get .Values $appName }}
{{/* Remove the Deployment if the app's restartDuringReconfig and the reconfigInProgress value are both true */}}
{{- if not (and $appValues.restartDuringReconfig .Values.reconfigInProgress) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}
spec:
  replicas: {{ $appValues.replicas }}
  strategy:
    type: {{ include "soh.deployment.strategy" (dict "Values" .Values "appValues" $appValues) }}
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
    spec:
      serviceAccount: gms-soh-elevated
      containers:
        - name: {{ $appName }}
          image: {{ include "soh.deployment.image" (dict "Values" .Values "appValues" $appValues) }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: GMS_CONFIG_SQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "postgres-read-only"
                  key: username
            - name: GMS_CONFIG_SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "postgres-read-only"
                  key: password
            {{- include "soh.app.deployment.env" (dict "appName" $appName "appEnv" $appValues.env "globalEnv" .Values.env "context" $) }}
{{- if or (and $appValues.cpu_requests $appValues.cpu_limit) (and $appValues.memory_requests $appValues.memory_limit)}}
          resources:
            requests:
{{- if ($appValues.cpu_requests)}}
              cpu: {{ $appValues.cpu_requests }}
{{- end }}
{{- if ($appValues.memory_requests)}}
              memory: {{ $appValues.memory_requests }}
{{- end }}
            limits:
{{- if ($appValues.cpu_limit)}}
              cpu: {{ $appValues.cpu_limit }}
{{- end }}
{{- if ($appValues.memory_limit)}}
              memory: {{ $appValues.memory_limit }}
{{- end }}
{{- end }}
{{- end }}
