{{- $appName := "postgresql-gms" }}
{{- $appValues := get .Values $appName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $appName }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ $appValues.storageSize }}
{{/* Remove the Deployment if the app's restartDuringReconfig and the reconfigInProgress value are both true */}}
{{- if not (and $appValues.restartDuringReconfig .Values.reconfigInProgress) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}
spec:
  replicas: {{ $appValues.replicas }}
  strategy:
    type: {{ include "soh.deployment.strategy" (dict "Values" .Values "appValues" $appValues) }}
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
    spec:
      serviceAccount: gms-soh-elevated
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "{{ $appName }}"
        - name: shm
          emptyDir:
            medium: Memory
      containers:
        - name: {{ $appName }}
          image: {{ include "soh.deployment.image" (dict "Values" .Values "appValues" $appValues) }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: "postgres-super-user"
                  key:  username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "postgres-super-user"
                  key: password
            - name: GMS_POSTGRES_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "postgres-admin"
                  key: password
            - name: GMS_POSTGRES_CONFIG_APPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "postgres-config-application"
                  key: password
            - name: GMS_POSTGRES_READ_ONLY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "postgres-read-only"
                  key: password
            - name: GMS_POSTGRES_SESSION_APPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "postgres-session-application"
                  key: password
            - name: GMS_POSTGRES_SOH_APPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "postgres-soh-application"
                  key: password
            - name: GMS_POSTGRES_SOH_TEST_APPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "postgres-soh-test-application"
                  key: password
            - name: GMS_POSTGRES_SOH_TTL_APPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "postgres-soh-ttl-application"
                  key: password
            {{- include "soh.app.deployment.env" (dict "appName" $appName "appEnv" $appValues.env "globalEnv" .Values.env "context" $) }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: shm
              mountPath: /dev/shm
{{- if or (and $appValues.cpu_requests $appValues.cpu_limit) (and $appValues.memory_requests $appValues.memory_limit)}}
          resources:
            requests:
{{- if ($appValues.cpu_requests)}}
              cpu: {{ $appValues.cpu_requests }}
{{- end }}
{{- if ($appValues.memory_requests)}}
              memory: {{ $appValues.memory_requests }}
{{- end }}
            limits:
{{- if ($appValues.cpu_limit)}}
              cpu: {{ $appValues.cpu_limit }}
{{- end }}
{{- if ($appValues.memory_limit)}}
              memory: {{ $appValues.memory_limit }}
{{- end }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: {{ $appName }}
