{{- $appName := "frameworks-osd-ttl-worker" }}
{{- $appValues := get .Values $appName }}
{{/* Remove the Deployment if the app's restartDuringReconfig and the reconfigInProgress value are both true */}}
{{- if not (and $appValues.restartDuringReconfig .Values.reconfigInProgress) }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $appName }}
spec:
  schedule: {{ $appValues.cronSchedule }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: gms-soh-elevated
          containers:
            - name: {{ $appName }}
              image: {{ include "soh.deployment.image" (dict "Values" .Values "appValues" $appValues) }}
              imagePullPolicy: {{ .Values.imagePullPolicy }}
              env:
                - name: DATA_SOURCE_USER
                  valueFrom:
                    secretKeyRef:
                      name: "postgres-admin"
                      key:  username
                - name: DATA_SOURCE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: "postgres-admin"
                      key:  password
                - name: GMS_CONFIG_OSD_TTL_WORKER__SQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: "postgres-soh-ttl-application"
                      key:  password
                {{- include "soh.app.deployment.env" (dict "appName" $appName "appEnv" $appValues.env "globalEnv" .Values.env "context" $) | indent 4 }}
              command:
                - /ttl/trigger-stored-procedure-once
          restartPolicy: OnFailure
{{- if or (and $appValues.cpu_requests $appValues.cpu_limit) (and $appValues.memory_requests $appValues.memory_limit)}}
          resources:
            requests:
{{- if ($appValues.cpu_requests)}}
              cpu: {{ $appValues.cpu_requests }}
{{- end }}
{{- if ($appValues.memory_requests)}}
              memory: {{ $appValues.memory_requests }}
{{- end }}
            limits:
{{- if ($appValues.cpu_limit)}}
              cpu: {{ $appValues.cpu_limit }}
{{- end }}
{{- if ($appValues.memory_limit)}}
              memory: {{ $appValues.memory_limit }}
{{- end }}
{{- end }}
{{- end }}
