---
apiVersion: v1
kind: Secret
metadata:
  name: "postgres-super-user"
type: Opaque
data:
  username: {{ "gms_super_user" | b64enc }}
  password: {{ .Values.password.postgres.gms_super_user | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "postgres-admin"
type: Opaque
data:
  username: {{ "gms_admin" | b64enc }}
  password: {{ .Values.password.postgres.gms_admin | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "postgres-config-application"
type: Opaque
data:
  username: {{ "gms_config_application"| b64enc }}
  password: {{ .Values.password.postgres.gms_config_application | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "postgres-read-only"
type: Opaque
data:
  username: {{ "gms_read_only" | b64enc }}
  password: {{ .Values.password.postgres.gms_read_only | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "postgres-session-application"
type: Opaque
data:
  username: {{ "gms_session_application"| b64enc }}
  password: {{ .Values.password.postgres.gms_session_application | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "postgres-soh-application"
type: Opaque
data:
  username: {{ "gms_soh_application"| b64enc }}
  password: {{ .Values.password.postgres.gms_soh_application | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "postgres-soh-test-application"
type: Opaque
data:
  username: {{ "gms_soh_test_application"| b64enc }}
  password: {{ .Values.password.postgres.gms_soh_test_application | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "postgres-soh-ttl-application"
type: Opaque
data:
  username: {{ "gms_soh_ttl_application"| b64enc }}
  password: {{ .Values.password.postgres.gms_soh_ttl_application | b64enc }}
