---
apiVersion: v1
kind: Secret
metadata:
  name: "etcd-gms-user"
type: Opaque
data:
  username: {{ "gms" | b64enc }}
  password: {{ .Values.password.etcd.gms | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "etcd-admin-user"
type: Opaque
data:
  username: {{ "gmsadmin" | b64enc }}
  password: {{ .Values.password.etcd.gmsadmin | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "etcd-root-user"
type: Opaque
data:
  username: {{ "root" | b64enc }}
  password: {{ .Values.password.etcd.root | b64enc }}
