NAME = etcd

BUILD_ARGS = --build-arg 'GMS_ETCD_PASSWORD=gmsdb:etcd:gms:packager-tungsten-sort' \
	     --build-arg 'GMS_ETCD_ADMIN_PASSWORD=gmsdb:etcd:gmsadmin:nonsaturated-southerns-souls' \
	     --build-arg 'GMS_ETCD_ROOT_PASSWORD=gmsdb:etcd:root:biophysicist-grandbaby-countermen'

include $(shell CI-MAKE-CONFIG-PATH)/Makefile.docker
